### PR TITLE
Reorganizes the project as a package

### PR DESCRIPTION
**Pull request by jimtyhurst**
This Pull Request changes the directory structure from an _ad hoc_ project to an [R package](https://r-pkgs.org). For the most part, I just moved files into the standard location required for a package:

* The data files moved into the `inst/extdata` directory.
* The `.R` files moved into the `R` directory.
* The `.Rmd` files moved into the `vignettes` directory.

Then I had to fix the references from the `.R` and `.Rmd` files to the data, because the data is accessed differently when it is in a package.

I also enhanced the documentation a bit.

Using an R package has several advantages:

* [RStudio](https://www.rstudio.com/products/rstudio/) and the [devtools](https://cran.r-project.org/package=devtools) package provide a lot of tooling that makes it easier to work with the data and code:
    - `.Rmd` files in the `vignettes` directory are run automatically during the build process to produce `html` and `md` files.
    - There is an explicit listing of package dependencies in the `DESCRIPTION` file.
    - Unit tests can be run automatically with `devtools::test()`.
    - Package and function documentation are generated automatically during the build process and are accessible from the console, e.g. `?'craggy2019-package'`.
    - `devtools::check()` does a lot of validation of code.
* The directory structure for data, code, and tests follows the standard conventions used by all R packages. That makes it easy for an experienced R developer to browse the project quickly.
* Packages simplify the process for developing reusable code that is accessible within this package or from other projects.  Rather than copying and pasting between `.Rmd` files, cRaggy participants can extract reusable code into functions defined in the package, which can then be re-used in multiple `.Rmd` files.
* The package structure also encourages the development of unit tests for code, because it is easy to write unit tests for code that has been isolated in a function definition.

We do not expect to ever make this package available to a wide audience. But using a package structure makes it easier for us cRaggy participants to write code and to generate analyses and visualizations to share with others.

### CODE REVIEW

**Comment by jimtyhurst** [comment]
Oops! I see a broken link in the [Introduction to Geospatial Visualization](https://github.com/jimtyhurst/craggy_2019/blob/as_pkg/vignettes/Introduction-to-Visualizing-Geospatial-Data.md) vignette. I will fix that before merging.

However, the other two vignettes seem to have been generated correctly in the new framework:

* [Demo OneNightCount.csv and vroom](https://github.com/jimtyhurst/craggy_2019/blob/as_pkg/vignettes/demo-1night-vroom-etc.md)
* [Looking at Evictions](https://github.com/jimtyhurst/craggy_2019/blob/as_pkg/vignettes/evictions.md)

**Review by smithjd — APPROVED** [review]
It looks good to me.  It adds another dimension to the whole experience so that will be worth discussing.  I'd say: merge it and let's have a look at the whole setup.

**Review by laderast — COMMENTED** [review]
I think this is very slick. My one question - we'll need to point people to the build tools in RStudio - are we going to scare newer users off by this?

**Comment by laderast** [comment]
Nevermind - I thought new users would have to access data in `inst/extdata` - I think this works really well.

**Comment by laderast** [comment]
I think we should probably put cleaned datasets into `data` with `usethis::use_data()` - that way they are easily accessible, so people could use `data(evictions)` to load them

**Comment by laderast** [comment]
More info here: https://www.erikhoward.net/how-to-create-an-r-data-package/

**Pull request merged**
